### ISSUE TITLE
I Have a problem - 

### ISSUE THREAD

**Issue by rennanvasconcellos** [dvarounis/perfservmon#13]
I am running the script is getting the following error. I am running the script is getting the following error. I tried to find the problem but to no avail.

**python perfservmon.py -C MYCELL retrieve -N MYHOST -P 9080**

Traceback (most recent call last):
  File "perfservmon.py", line 804, in <module>
    parseperfxml(path=startingpath, cellname=arguments.CellName)
  File "perfservmon.py", line 466, in parseperfxml
    with shelve.open(shelvefilename, flag='c') as pfile:
AttributeError: DbfilenameShelf instance has no attribute '__exit__'

**python perfservmon.py -C wasbase show -n cell -s trnp300 -M Heap -c 90 -w 70**
UNKNOWN - Error opening cached metrics file

**Comment by dvarounis** [comment]
It seems to be an issue with Context Manager on Python 2.7. You may use version 1.5.1(https://github.com/dvarounis/perfservmon/releases/tag/1.5.1 ) as a temporary workaround until I fix it.
Thanks for submitting your issue!

**Comment by rennanvasconcellos** [comment]
error still occurs :(

My name cell: wasbase
My name Node: cell

**Command**: python perfservmon.py -C wasbase show -n "cell" -s trnp300 -M Heap
**Output:** UNKNOWN - Not available statistics for server cell.trnp300

**Comment by rennanvasconcellos** [comment]
error still occurs :(

My name cell: wasbase
My name Node: cell

**Command:** python perfservmon.py -C wasbase show -n cell -s trnp300 -M Heap
**Output:** UNKNOWN - Not available statistics for server cell.trnp300

**Comment by rennanvasconcellos** [comment]
this command is ok

**Command:** python perfservmon.py -C wasbase retrieve -N trnp300 -P 9080
**Output:** OK - PerfServlet Data refreshed on Tue Jan  8 13:59:54 2019

**Comment by dvarounis** [comment]
One way to debug this is commenting out the following section in perfservmon.py:
```
# Comment out for debug purposes
# was.printserver()
```
Then run `retrieve` call again and check whether the correct cell/node/server and the required metric is present.
A (slightly) possible reason for not getting Heap metrics is that the WAS PMI has not enabled the specific metric.
