### ISSUE TITLE
issue with perfservermon.py when executed

### ISSUE THREAD

**Issue by arjunharidasp** [dvarounis/perfservmon#14]
I need to use perfservermon.py for monitoring my WAS parmeters

What I have done : Installed and configured perfservlet

Perfservlet is accessible fine.

but while running the perfservmon.py command from Nagios Server. I'm getting the below error

/usr/local/nagios/libexec/perfservermon.py -C xxx retrieve -N server.example.com/wasPerfTool/servlet/perfservlet -P 9080 -u xxx -p xxx --ignorecert -H http

Traceback (most recent call last):
  File "/usr/local/nagios/libexec/perfservermon.py", line 801, in <module>
    username=arguments.Username, password=arguments.Password)
  File "/usr/local/nagios/libexec/perfservermon.py", line 658, in retrieveperfxml
    tree = parse(xmlfilename)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 35, column 2

# python -V
Python 2.7.15+

Can you please tell me what i'm doing wrong

**Comment by dvarounis** [comment]
`xml.etree.ElementTree.ParseError: mismatched tag: line 35, column 2`
There seems to be a problem with perfservlet xml parsing.
Can you send the line 35 of perfservlet xml?

**Comment by arjunharidasp** [comment]
Here you go with the requested details

see the below lines from 30 to 40

<TimeStatistic ID="2" lastSampleTime="1574067515900" max="0" min="0" name="EJBAuthorizationTime" startTime="1574067515900" totalTime="0" unit="Milliseconds"/>
<TimeStatistic ID="3" lastSampleTime="1575350191028" max="1" min="0" name="AdminAuthorizationTime" startTime="1574067515900" totalTime="3" unit="Milliseconds"/>
</Stat>
<Stat name="SIB Service">
<Stat name="StatGroup.Communications">
**35  <Stat name="StatGroup.Clients">**
<Stat name="StatGroup.ClientsDetailed"/>
<Stat name="StatGroup.ClientsStandard"/>
</Stat>
<Stat name="StatGroup.MessagingEngines">
<Stat name="StatGroup.MessagingEnginesDetailed"/>
<Stat name="StatGroup.MessagingEnginesStandard"/>

**Comment by arjunharidasp** [comment]
Line 35 

1. Stat name="StatGroup.Clients"

**Comment by dvarounis** [comment]
@arjunharidasp This is an xml file. The line you mention should be like:
`<Stat name="StatGroup.Clients">`

**Comment by arjunharidasp** [comment]
The line is same

i just removed the braces for pasting

`<Stat name="StatGroup.Clients">`
