### ISSUE TITLE
SIB Destinations in clusters

### ISSUE THREAD

**Issue by atterdag** [dvarounis/perfservmon#8]
Hi Dimos

If you have a SIB with a cluster as member, then only one server in the cluster runs the engine at a time (except if choosing the "Scalability with HA" policy).

So as the script works currently, if you have 4 servers in a cluster, then you must configure a SIB destination check for each server, thus resulting in 3 UNKNOWN, and one OK message.

I suggest that we add a "cluster" switch to SIB destination check, so that perfservmon doesn't return a UNKNOWN, but "OK: inactive SIB engine" for cluster nodes that doesn't run the engine, as a way of saying "Yeah, yeah I know there's no data, but its expected" to Nagios.

Or do you have a better idea?

**Comment by dvarounis** [comment]
Hello @atterdag ,
Nice idea!
However It depends on the information that perfservlet returns in the case you describe.
 I have found some differences of the "SIB Service" caption in the perfservlet xml when a cluster node does not hold an active ME versus when it does.
I will take a look at what can be done with this.

**Comment by dvarounis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Perfservmon Maintenance](https://trello.com/c/rlq1XAHj/64-perfservmon-maintenance)

**Comment by atterdag** [comment]
Yes each servers in the cluster will have a list of elements under `<Stat name="SIB Messaging Engines"\>` with SIB engines names - for instance `<Stat name="PortalCluster.000-IWKBus">`. But only the active server will have a `<Stat name="Destinations">` under `<Stat name="PortalCluster.000-IWKBus">`.

So we can certainly build a logic to interpret this.

**Comment by dvarounis** [comment]
@atterdag Please check the updated version
