### ISSUE TITLE
Syntax issue

### ISSUE THREAD

**Issue by elizadizon** [dvarounis/perfservmon#9]
I am receiving this error when running the retrieval command: 
except urllib2.HTTPError as error: 
^SyntaxError: invalid syntax

Is this due to the python version?
Version 2.4.3 is running on this machine

**Comment by dvarounis** [comment]
Yes, unfortunately this is due to Python version.
At this moment **perfservmon** runs only on Python 2.7.
My plans are to support it for newer Python versions (i.e. Python 3), not older ones.
